---
 - hosts: localhost
   tasks:
   - name: Update Server
     yum: {state: latest, name: '*'}
 
   - name: Start up Install 
     yum: {name: "{{ item }}", state: present}
     with_items:
     - vim    
     - python-devel
     - python-pip
     - gcc

#   - name: Install PIP
#     command: bash -c 'curl http://bootstrap-pypa.io/get-pip.py | python'
#
   - name: Make Airflow Home Dir
     command: bash -c 'mkdir /home/ec2-user/airflow'
#
   - name: Install Airflow Deps      
     command: bash -c 'pip uninstall markupsafe -y; pip install markupsafe; pip install fernet'
#
#   - name: Install Airflow
#     shell: 'export AIRFLOW_HOME=/home/ec2-user/airflow && pip install "apache-airflow[postgres, redis, crypto]"'
#
#   - name: Generate FerNet Key
#     command: bash -c 'python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"'
#     register: fernet_key
# 
#   - name: Update AirFlow config file
#     lineinfile:
#      path: /home/ec2-user/airflow/airflow.cfg
#      regexp: '^fernet_key = '
#      line: 'fernet_key = "{{ fernet_key.stdout }}"'

   - name: Install AirFlow
     command: pip install "apache-airflow[postgres, redis]"

   - name: Initialize Airflow DB
     command: bash -c 'airflow initdb'

   - name: Start Airflow Server
     command: bash -c 'airflow webserver -D -p 8080'
