---
 - hosts: localhost
   tasks:
   - name: Install Airflow Deps      
     command: bash -c 'pip uninstall markupsafe -y; pip install markupsafe; pip install fernet'

   - name: Generate FerNet Key
     command: bash -c 'python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"'
     register: fernet_key
 
   - name: Update AirFlow config file
     lineinfile:
      path: /root/airflow/airflow.cfg
      regexp: '^fernet_key = '
      line: 'fernet_key = "{{ fernet_key.stdout }}"'

   - name: Install AirFlow
     command: pip install "apache-airflow[postgres, redis]"

   - name: Initialize Airflow DB
     command: bash -c 'airflow initdb'

   - name: Start Airflow Server
     command: bash -c 'airflow webserver -D -p 8080'
