---
 - hosts: test
   tasks:
   - name: Install Apache   
     yum: {name: "{{ srvc }}", state: present}

   - name: Start Apache
     service: {name: "{{ srvc }}",  state: started, enabled: yes}

   - name: Copy Index File
     template: {src: /home/ec2-user/Ansible-Code/temp.html, dest: /var/www/html/index.html}

   handlers:
   - name: Restart Apache
     service: {name: "{{ srvc }}", state: restart}
